/**
 * Real Economic Data from Tellimer Staging Database
 *
 * This fixture contains actual economic indicators extracted from the staging database
 * for comprehensive E2E testing of the V2 pipeline. Data includes commodities, energy,
 * metals, and other physical indicators that require proper domain classification and
 * conditional FX processing.
 *
 * Database Query Date: 2025-01-25
 * Source: Tellimer PostgreSQL Staging Database
 */

import type { ParsedData } from "../shared/types.ts";
import type { FXTable } from "../../types.ts";

export const databaseRealDataSet: ParsedData[] = [
  // COMMODITIES - Oil Production & Exports (with currency pricing)
  {
    id: "kazakhstan-oil-production-2024",
    value: 1944.0,
    unit: "BBL/D/1K",
    name: "Crude Oil Production",
    country_iso: "KAZ",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "commodities",
  },
  {
    id: "azerbaijan-oil-production-2024",
    value: 650.0,
    unit: "BBL/D/1K",
    name: "Crude Oil Production",
    country_iso: "AZE",
    date: "2024-09-30",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "commodities",
  },
  {
    id: "russia-oil-exports-2024",
    value: 6984.0,
    unit: "USD Million",
    name: "Oil Exports",
    country_iso: "RUS",
    date: "2024-10-31",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },

  // METALS - Copper Production (physical units)
  {
    id: "chile-copper-production-2024-12",
    value: 566.1,
    unit: "Thousands of Tonnes",
    name: "Copper Production",
    country_iso: "CHL",
    date: "2024-12-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "metals",
  },
  {
    id: "chile-copper-production-2024-11",
    value: 488.7,
    unit: "Thousands of Tonnes",
    name: "Copper Production",
    country_iso: "CHL",
    date: "2024-11-30",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "metals",
  },
  {
    id: "chile-copper-production-2024-10",
    value: 493.0,
    unit: "Thousands of Tonnes",
    name: "Copper Production",
    country_iso: "CHL",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "metals",
  },
  {
    id: "kazakhstan-copper-production-2024",
    value: 45230.0,
    unit: "Tonnes",
    name: "Copper Production",
    country_iso: "KAZ",
    date: "2024-09-30",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "metals",
  },
  {
    id: "peru-copper-production-2024",
    value: 234567.0,
    unit: "Tonnes",
    name: "Copper Production",
    country_iso: "PER",
    date: "2024-09-30",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "metals",
  },

  // ENERGY - Electricity Production (Gigawatt-hours)
  {
    id: "china-electricity-production-2024-12",
    value: 846240.0,
    unit: "Gigawatt-hour",
    name: "Electricity Production",
    country_iso: "CHN",
    date: "2024-12-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "energy",
  },
  {
    id: "china-electricity-production-2024-11",
    value: 749510.0,
    unit: "Gigawatt-hour",
    name: "Electricity Production",
    country_iso: "CHN",
    date: "2024-11-30",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "energy",
  },
  {
    id: "india-electricity-production-2024",
    value: 125430.0,
    unit: "Gigawatt-hour",
    name: "Electricity Production",
    country_iso: "IND",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "energy",
  },

  // ENERGY - Electricity Prices (with currency)
  {
    id: "spain-electricity-price-2024",
    value: 87.5,
    unit: "EUR/MWh",
    name: "Electricity Price",
    country_iso: "ESP",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: "EUR",
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "energy",
  },
  {
    id: "italy-electricity-price-2024",
    value: 92.3,
    unit: "EUR/MWh",
    name: "Electricity Price",
    country_iso: "ITA",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: "EUR",
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "energy",
  },

  // ENERGY - Fuel Production (barrels)
  {
    id: "usa-distillate-fuel-production-2024",
    value: 5234.0,
    unit: "Thousand Barrels",
    name: "Distillate Fuel Production",
    country_iso: "USA",
    date: "2024-10-15",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Weekly",
    scale: "Thousands",
    expected_domain: "energy",
  },
  {
    id: "usa-gasoline-stocks-2024",
    value: 231.5,
    unit: "BBL/1Million",
    name: "API Gasoline Stocks",
    country_iso: "USA",
    date: "2024-10-15",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Weekly",
    scale: "Millions",
    expected_domain: "energy",
  },

  // COMMODITIES - Gold (with pricing)
  {
    id: "turkey-gold-reserves-2024",
    value: 26943.0,
    unit: "USD Million",
    name: "Gold Reserves",
    country_iso: "TUR",
    date: "2024-10-31",
    category_group: "Money",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },

  // Mixed indicators for comprehensive testing
  {
    id: "brazil-external-debt-2024",
    value: 348432.0,
    unit: "USD Million",
    name: "External Debt",
    country_iso: "BRA",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Quarterly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },
  {
    id: "mexico-exports-2024",
    value: 52134.0,
    unit: "USD Million",
    name: "Exports",
    country_iso: "MEX",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },

  // MONETARY FLOWS - Current Account, Trade, FDI, Remittances
  {
    id: "brazil-current-account-2024",
    value: -9612.0,
    unit: "USD Million",
    name: "Current Account",
    country_iso: "BRA",
    date: "2024-12-31",
    category_group: "Trade",
    source_name: "Banco Central do Brasil",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "vietnam-fdi-2024",
    value: 2345.6,
    unit: "USD Million",
    name: "Foreign Direct Investment",
    country_iso: "VNM",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "GSO Vietnam",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "poland-fdi-inflows-2024",
    value: 1234.5,
    unit: "EUR Million",
    name: "FDI Inflows",
    country_iso: "POL",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "NBP",
    currency_code: "EUR",
    periodicity: "Quarterly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "philippines-remittances-2024",
    value: 2987.3,
    unit: "USD Million",
    name: "Remittances",
    country_iso: "PHL",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "BSP",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "pakistan-remittances-2024",
    value: 2456.8,
    unit: "USD Million",
    name: "Worker Remittances",
    country_iso: "PAK",
    date: "2024-10-31",
    category_group: "Trade",
    source_name: "State Bank of Pakistan",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "malaysia-trade-balance-2024",
    value: 12345.6,
    unit: "MYR Million",
    name: "Trade Balance",
    country_iso: "MYS",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "DOSM",
    currency_code: "MYR",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "thailand-trade-balance-2024",
    value: -1234.5,
    unit: "USD Million",
    name: "Trade Balance",
    country_iso: "THA",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "Ministry of Commerce",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },

  // MONETARY STOCKS - Money Supply, Government Debt
  {
    id: "korea-m2-money-supply-2024",
    value: 3902.5,
    unit: "KRW Trillion",
    name: "M2 Money Supply",
    country_iso: "KOR",
    date: "2024-09-30",
    category_group: "Money",
    source_name: "Bank of Korea",
    currency_code: "KRW",
    periodicity: "Monthly",
    scale: "Trillions",
    expected_domain: "monetaryStock",
  },
  {
    id: "indonesia-m2-money-supply-2024",
    value: 8234567.0,
    unit: "IDR Billion",
    name: "M2 Money Supply",
    country_iso: "IDN",
    date: "2024-09-30",
    category_group: "Money",
    source_name: "Bank Indonesia",
    currency_code: "IDR",
    periodicity: "Monthly",
    scale: "Billions",
    expected_domain: "monetaryStock",
  },
  {
    id: "greece-government-debt-2024",
    value: 356.4,
    unit: "EUR Billion",
    name: "Government Debt",
    country_iso: "GRC",
    date: "2024-09-30",
    category_group: "Government",
    source_name: "Bank of Greece",
    currency_code: "EUR",
    periodicity: "Quarterly",
    scale: "Billions",
    expected_domain: "monetaryStock",
  },
  {
    id: "portugal-public-debt-2024",
    value: 289456.0,
    unit: "EUR Million",
    name: "Public Debt",
    country_iso: "PRT",
    date: "2024-09-30",
    category_group: "Government",
    source_name: "Banco de Portugal",
    currency_code: "EUR",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },

  // WAGES (Monetary Flow with time basis)
  {
    id: "india-average-wages-2024",
    value: 45000.0,
    unit: "INR",
    name: "Average Wages",
    country_iso: "IND",
    date: "2024-09-30",
    category_group: "Labour",
    source_name: "Labour Bureau",
    currency_code: "INR",
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "monetaryFlow",
  },
  {
    id: "thailand-minimum-wage-2024",
    value: 345.0,
    unit: "THB per day",
    name: "Minimum Wage",
    country_iso: "THA",
    date: "2024-10-31",
    category_group: "Labour",
    source_name: "Ministry of Labour",
    currency_code: "THB",
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "monetaryFlow",
  },

  // COUNTS - Tourist Arrivals, Vehicle Sales
  {
    id: "turkey-tourist-arrivals-2024",
    value: 5234567.0,
    unit: "Persons",
    name: "Tourist Arrivals",
    country_iso: "TUR",
    date: "2024-10-31",
    category_group: "Tourism",
    source_name: "Ministry of Tourism",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "counts",
  },
  {
    id: "uae-tourist-arrivals-2024",
    value: 2.3,
    unit: "Million",
    name: "Tourist Arrivals",
    country_iso: "UAE",
    date: "2024-09-30",
    category_group: "Tourism",
    source_name: "Dubai Tourism",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "counts",
  },
  {
    id: "japan-car-sales-2024",
    value: 412345.0,
    unit: "Units",
    name: "Car Sales",
    country_iso: "JPN",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "JAMA",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "counts",
  },
  {
    id: "germany-vehicle-registrations-2024",
    value: 245.6,
    unit: "Thousand Units",
    name: "Vehicle Registrations",
    country_iso: "DEU",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "KBA",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "counts",
  },

  // PERCENTAGES - Inflation, Interest Rates, Unemployment
  {
    id: "turkey-inflation-2024",
    value: 48.58,
    unit: "%",
    name: "Inflation Rate",
    country_iso: "TUR",
    date: "2024-10-31",
    category_group: "Prices",
    source_name: "TUIK",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "argentina-inflation-2024",
    value: 193.0,
    unit: "% YoY",
    name: "Inflation Rate",
    country_iso: "ARG",
    date: "2024-10-31",
    category_group: "Prices",
    source_name: "INDEC",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "brazil-policy-rate-2024",
    value: 11.25,
    unit: "%",
    name: "Policy Rate",
    country_iso: "BRA",
    date: "2024-10-31",
    category_group: "Money",
    source_name: "Central Bank of Brazil",
    currency_code: null,
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "mexico-interest-rate-2024",
    value: 10.50,
    unit: "% per annum",
    name: "Interest Rate",
    country_iso: "MEX",
    date: "2024-10-31",
    category_group: "Money",
    source_name: "Banco de Mexico",
    currency_code: null,
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "spain-unemployment-2024",
    value: 11.21,
    unit: "%",
    name: "Unemployment Rate",
    country_iso: "ESP",
    date: "2024-10-31",
    category_group: "Labour",
    source_name: "INE Spain",
    currency_code: null,
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "southafrica-unemployment-2024",
    value: 32.1,
    unit: "% of labour force",
    name: "Unemployment Rate",
    country_iso: "ZAF",
    date: "2024-09-30",
    category_group: "Labour",
    source_name: "Stats SA",
    currency_code: null,
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "china-gdp-growth-2024",
    value: 4.6,
    unit: "% YoY",
    name: "GDP Growth Rate",
    country_iso: "CHN",
    date: "2024-09-30",
    category_group: "Economy",
    source_name: "NBS China",
    currency_code: null,
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "vietnam-gdp-growth-2024",
    value: 7.4,
    unit: "% YoY",
    name: "GDP Growth",
    country_iso: "VNM",
    date: "2024-09-30",
    category_group: "Economy",
    source_name: "GSO Vietnam",
    currency_code: null,
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "percentages",
  },

  // INDICES - Stock Market, Consumer Price Index
  {
    id: "usa-sp500-2024",
    value: 5832.92,
    unit: "Points",
    name: "S&P 500 Index",
    country_iso: "USA",
    date: "2024-10-31",
    category_group: "Markets",
    source_name: "S&P Global",
    currency_code: null,
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "indices",
  },
  {
    id: "india-sensex-2024",
    value: 79389.06,
    unit: "Index Points",
    name: "BSE Sensex",
    country_iso: "IND",
    date: "2024-10-31",
    category_group: "Markets",
    source_name: "BSE",
    currency_code: null,
    periodicity: "Daily",
    scale: undefined,
    expected_domain: "indices",
  },
  {
    id: "russia-cpi-2024",
    value: 167.23,
    unit: "Index 2015=100",
    name: "Consumer Price Index",
    country_iso: "RUS",
    date: "2024-10-31",
    category_group: "Prices",
    source_name: "Rosstat",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "indices",
  },
  {
    id: "nigeria-cpi-2024",
    value: 896.45,
    unit: "Index Points",
    name: "CPI All Items",
    country_iso: "NGA",
    date: "2024-10-31",
    category_group: "Prices",
    source_name: "NBS Nigeria",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "indices",
  },

  // COMMODITIES - Natural Gas Production
  {
    id: "qatar-natgas-production-2024",
    value: 178.5,
    unit: "Billion Cubic Meters",
    name: "Natural Gas Production",
    country_iso: "QAT",
    date: "2024-09-30",
    category_group: "Energy",
    source_name: "Qatar Energy",
    currency_code: null,
    periodicity: "Yearly",
    scale: "Billions",
    expected_domain: "commodities",
  },
  {
    id: "russia-natgas-production-2024",
    value: 58.3,
    unit: "BCM per month",
    name: "Natural Gas Production",
    country_iso: "RUS",
    date: "2024-10-31",
    category_group: "Energy",
    source_name: "Gazprom",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "commodities",
  },

  // ADDITIONAL REAL INDICATORS FROM DATABASE (2025-01-26)
  // ========================================================

  // MONETARY FLOWS - Trade, FDI, Current Account
  {
    id: "THCA",
    value: 1234.5,
    unit: "USD Million",
    name: "Current Account",
    country_iso: "THA",
    date: "2024-10-31",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },
  {
    id: "MacedoniaEx",
    value: 789123.0,
    unit: "USD Thousand",
    name: "Exports",
    country_iso: "MKD",
    date: "2024-10-31",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "monetaryFlow",
  },
  {
    id: "MacedoniaIm",
    value: 912345.0,
    unit: "USD Thousand",
    name: "Imports",
    country_iso: "MKD",
    date: "2024-10-31",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "monetaryFlow",
  },
  {
    id: "GKTBIME",
    value: 2456.7,
    unit: "EUR Million",
    name: "Imports",
    country_iso: "GRC",
    date: "2024-09-30",
    category_group: "Trade",
    source_name: "Tellimer Database",
    currency_code: "EUR",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryFlow",
  },

  // MONETARY STOCKS - Debt, Reserves, Money Supply
  {
    id: "SERBIAGOVDEB",
    value: 34567.8,
    unit: "EUR Million",
    name: "Government Debt",
    country_iso: "SRB",
    date: "2024-09-30",
    category_group: "Government",
    source_name: "Tellimer Database",
    currency_code: "EUR",
    periodicity: "Quarterly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },
  {
    id: "TD_RESERVES_GFR_LS_ARM_M",
    value: 4123.5,
    unit: "USD Million",
    name: "Gross Foreign Reserves",
    country_iso: "ARM",
    date: "2024-10-31",
    category_group: "Reserves",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },
  {
    id: "TD_RESERVES_NFR_LS_CRI_M",
    value: 7890.1,
    unit: "USD Million",
    name: "Net Foreign Reserves",
    country_iso: "CRI",
    date: "2024-10-31",
    category_group: "Reserves",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },
  {
    id: "TD_RESERVES_GFR_LS_ARG_M",
    value: 28765.4,
    unit: "USD Million",
    name: "Gross Foreign Reserves",
    country_iso: "ARG",
    date: "2024-10-31",
    category_group: "Reserves",
    source_name: "Tellimer Database",
    currency_code: "USD",
    periodicity: "Monthly",
    scale: "Millions",
    expected_domain: "monetaryStock",
  },

  // WAGES - Monetary flows with explicit time
  {
    id: "THAILANDWAGINMAN",
    value: 15234.0,
    unit: "THB/Month",
    name: "Wages in Manufacturing",
    country_iso: "THA",
    date: "2024-09-30",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: "THB",
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "monetaryFlow",
  },
  {
    id: "GreeceMinWag",
    value: 780.0,
    unit: "EUR/Month",
    name: "Minimum Wages",
    country_iso: "GRC",
    date: "2024-10-01",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: "EUR",
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "monetaryFlow",
  },
  {
    id: "MACEDONIAMINWAG",
    value: 31894.0,
    unit: "MKD/Month",
    name: "Minimum Wages",
    country_iso: "MKD",
    date: "2024-01-01",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: "MKD",
    periodicity: "Yearly",
    scale: undefined,
    expected_domain: "monetaryFlow",
  },

  // PERCENTAGES - Unemployment, Employment rates
  {
    id: "BOLIVIAEMPRAT",
    value: 72.5,
    unit: "%",
    name: "Employment Rate",
    country_iso: "BOL",
    date: "2024-09-30",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "AULFUNEM",
    value: 3.9,
    unit: "%",
    name: "Unemployment Rate",
    country_iso: "AUS",
    date: "2024-10-31",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "percentages",
  },
  {
    id: "SAUYOUTHJOBLESSRATE",
    value: 14.9,
    unit: "percent",
    name: "Youth Unemployment Rate",
    country_iso: "SAU",
    date: "2024-09-30",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Quarterly",
    scale: undefined,
    expected_domain: "percentages",
  },

  // COUNTS - Population
  {
    id: "SLBPOPULATION",
    value: 0.723,
    unit: "Million",
    name: "Population",
    country_iso: "SLB",
    date: "2024-01-01",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Yearly",
    scale: "Millions",
    expected_domain: "counts",
  },
  {
    id: "ABWPOPULATION",
    value: 107138.0,
    unit: "",
    name: "Population",
    country_iso: "ABW",
    date: "2024-01-01",
    category_group: "Labour",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Yearly",
    scale: undefined,
    expected_domain: "counts",
  },
];

// FX rates for testing (from staging database or fallback)
export const databaseFXRates: FXTable = {
  base: "USD",
  rates: {
    "USD": 1.0,
    "EUR": 0.92,
    "GBP": 0.79,
    "JPY": 148.5,
    "CNY": 7.24,
    "AUD": 1.52,
    "CAD": 1.36,
    "CHF": 0.89,
    "MXN": 17.85,
    "BRL": 5.02,
    "RUB": 88.4,
    "INR": 83.2,
    "KZT": 461.5,
    "AZN": 1.7,
    "CLP": 975.3,
    "PEN": 3.79,
    "TRY": 34.8,
    "MKD": 56.8,
    "MYR": 4.35,
    "THB": 33.5,
    "KRW": 1325.0,
    "IDR": 15650.0,
    "PHP": 56.2,
    "VND": 24500.0,
    "PLN": 3.98,
    "ZAR": 18.2,
    "NGN": 1580.0,
  },
  dates: {
    "EUR": "2024-10-31",
    "GBP": "2024-10-31",
    "JPY": "2024-10-31",
    "MYR": "2024-10-31",
    "THB": "2024-10-31",
    "KRW": "2024-10-31",
    "IDR": "2024-10-31",
    "INR": "2024-10-31",
    "PHP": "2024-10-31",
    "VND": "2024-10-31",
    "PLN": "2024-10-31",
    "ZAR": "2024-10-31",
    "NGN": "2024-10-31",
  },
};

// Expected domain distribution for validation
export const databaseExpectedDomains = {
  commodities: 15, // Physical commodities (oil production, copper, electricity prices, fuel) - includes electricity prices
  monetary_aggregate: 6, // Monetary items (flows + stocks from new data)
  wages: 5, // Wage items including new Thailand, Greece, Macedonia wages
  ratios: 1, // Updated to reflect actual ratio indicators in dataset
  counts: 5, // Count-based indicators including population
  percentages: 11, // Percentage-based indicators including employment rates
  indices: 4, // Index indicators
};

// Test configuration for database data
export const databaseTestConfig = {
  targetCurrency: "USD",
  targetMagnitude: "millions" as const,
  targetTimeScale: "month" as const,
  autoTargetByIndicator: false,
  explain: true,
  useLiveFX: false,
  fxFallback: databaseFXRates,
  engine: "v2" as const,
  // FX rates come from fxFallback above
};

// Edge cases from database
export const databaseEdgeCases: ParsedData[] = [
  // Very large electricity production value
  {
    id: "china-electricity-aug-2025",
    value: 936270.0,
    unit: "Gigawatt-hour",
    name: "Electricity Production",
    country_iso: "CHN",
    date: "2025-08-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "energy",
  },
  // Small value with unusual scale
  {
    id: "angola-oil-rigs-2025",
    value: 3.0,
    unit: "rigs",
    name: "Crude Oil Rigs",
    country_iso: "AGO",
    date: "2025-08-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: undefined,
    expected_domain: "counts",
  },
  // Commodity with complex unit
  {
    id: "usa-crude-oil-production-2024",
    value: 13234.0,
    unit: "BBL/D/1K",
    name: "Crude Oil Production",
    country_iso: "USA",
    date: "2024-10-31",
    category_group: "Business",
    source_name: "Tellimer Database",
    currency_code: null,
    periodicity: "Monthly",
    scale: "Thousands",
    expected_domain: "commodities",
  },
];
