# Development Docker Compose
# Only database services - use local Restate server via `bun run dev:local`

services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    environment:
      POSTGRES_USER: classify
      POSTGRES_PASSWORD: classify
      POSTGRES_DB: classify
    ports:
      - "5432:5432"
    volumes:
      - timescale-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U classify"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: postgres -c shared_preload_libraries=timescaledb

volumes:
  timescale-data:
