# Simple Multi-Node Setup (NOT a real cluster, but gives 3x throughput)
# Each node is independent - no shared state, but you get parallel processing

version: '3.8'

services:
  # Node 1 with its own data
  restate-node-1:
    image: docker.io/restatedev/restate:latest
    restart: unless-stopped
    ports:
      - "8080:8080"   # Ingress
      - "9070:9070"   # Admin
      - "5122:5122"   # Node RPC
    environment:
      RUST_LOG: info
    volumes:
      - restate-data-1:/restate-data

  # Node 2 with its own data
  restate-node-2:
    image: docker.io/restatedev/restate:latest
    restart: unless-stopped
    ports:
      - "8081:8080"   # Ingress
      - "9071:9070"   # Admin
      - "5123:5122"   # Node RPC
    environment:
      RUST_LOG: info
    volumes:
      - restate-data-2:/restate-data

  # Node 3 with its own data
  restate-node-3:
    image: docker.io/restatedev/restate:latest
    restart: unless-stopped
    ports:
      - "8082:8080"   # Ingress
      - "9072:9070"   # Admin
      - "5124:5122"   # Node RPC
    environment:
      RUST_LOG: info
    volumes:
      - restate-data-3:/restate-data

volumes:
  restate-data-1:
  restate-data-2:
  restate-data-3:
