x-defaults: &defaults
  image: docker.io/restatedev/restate:latest
  restart: unless-stopped
  volumes:
    - restate-data:/restate-data

x-common-env: &common-env
  RESTATE_CLUSTER_NAME: restate-cluster
  RESTATE_BIFROST_PROVIDER: local
  RESTATE_BIFROST_LOCAL_LOGLET_PROVIDER: in_memory
  # Restate replicated mode requires a persistent shared storage for bifrost, such as S3.
  # For simplicity, we use minio as a local S3-compatible storage.
  RESTATE_BIFROST_REPLICATED_LOGLET_PROVIDER: s3
  AWS_ACCESS_KEY_ID: minioadmin
  AWS_SECRET_ACCESS_KEY: minioadmin
  AWS_ENDPOINT: http://minio:9000
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: restate

services:
  restate-1:
    <<: *defaults
    ports:
      - "8080:8080" # Ingress
      - "9070:9070" # Admin
      - "5122:5122" # Node-to-node communication
    environment:
      <<: *common-env
      RESTATE_NODE_NAME: restate-1
      RESTATE_FORCE_NODE_ID: 1
      RESTATE_ADVERTISED_ADDRESS: "http://restate-1:5122" # Other Restate nodes must be able to reach us using this address
      RESTATE_AUTO_PROVISION: "true" # Only the first node provisions the cluster

  restate-2:
    <<: *defaults
    ports:
      - "25122:5122"
      - "29070:9070"
      - "28080:8080"
    environment:
      <<: *common-env
      RESTATE_NODE_NAME: restate-2
      RESTATE_FORCE_NODE_ID: 2
      RESTATE_ADVERTISED_ADDRESS: "http://restate-2:5122"
      RESTATE_AUTO_PROVISION: "false"

  restate-3:
    <<: *defaults
    ports:
      - "35122:5122"
      - "39070:9070"
      - "38080:8080"
    environment:
      <<: *common-env
      RESTATE_NODE_NAME: restate-3
      RESTATE_FORCE_NODE_ID: 3
      RESTATE_ADVERTISED_ADDRESS: "http://restate-3:5122"
      RESTATE_AUTO_PROVISION: "false"

  minio:
    image: quay.io/minio/minio
    entrypoint: "/bin/sh"
    # Ensure a bucket called "restate" exists on startup:
    command: "-c 'mkdir -p /data/restate && /usr/bin/minio server --quiet /data'"
    ports:
      - "9000:9000"

# We create a volume to persist data across container starts; delete it via `docker volume rm restate-data` if you want to start a fresh cluster
volumes:
  restate-data:
