# Restate Server Configuration
# https://docs.restate.dev/operate/configuration/server

# Tracing configuration (required)
tracing-filter = "info"

[worker.ingress_http]
bind_address = "0.0.0.0:8080"

[admin]
bind_address = "0.0.0.0:9070"

[worker]
# Increase command batch size for higher throughput
max_command_batch_size = 128

[worker.invoker]
# Increase abort timeout to 10 minutes for LLM calls
abort_timeout = "10m"

# Global max retry attempts (backstop for services that don't specify maxRetries)
# Individual run blocks with maxRetries take precedence
max_retry_attempts = 5

# Inactivity timeout - abort if no progress for 5 minutes
inactivity_timeout = "5m"

# Increase concurrent invocations for high throughput (default: 1000)
concurrent_invocations_limit = 5000

# Increase in-memory queue to handle burst of workflows
in_memory_queue_length_limit = 100000
