#!/usr/bin/env -S deno run --allow-read --allow-write
/**
 * Apply agent classifications to test fixtures
 */

export const agentClassifications = {
  ALBANIABUSCON: {
    family: "qualitative",
    indicator_type: "sentiment",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  UFX_WB_GNB_XOF: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  ALBANIAECOOPTIND: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  UFX_WB_MWI_MWK: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  ALBANIAEMPRAT: {
    family: "numeric-measurement",
    indicator_type: "percentage",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  TM_RPCH: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "neutral",
  },
  AUSTRALIAMANPMI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  USASOFR: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
  },
  FINLANDFACORD: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  AUSTRALIAPRISECCRE: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  AUSTRALIAPRIINV: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  AUSBCE: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  UFX_WB_MLI_XOF: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  AUTNGI: {
    family: "physical-fundamental",
    indicator_type: "volume",
    temporal_aggregation: "period-total",
    heat_map_orientation: "neutral",
  },
  ANGOLAINTRAT: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  USADFSRI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  CANCPITRI: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "lower-is-positive",
  },
  UNITEDSTAADPEMPCHA: {
    family: "numeric-measurement",
    indicator_type: "count",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
  },
  "NY.GDP.PCAP.CD": {
    family: "numeric-measurement",
    indicator_type: "ratio",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  USANHSM: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  "SL.UEM.TOTL.ZS": {
    family: "numeric-measurement",
    indicator_type: "percentage",
    temporal_aggregation: "not-applicable",
    heat_map_orientation: "lower-is-positive",
  },
  ALBANIARETSYOY: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  TD_RESERVES_TRRCEMAC_LS_CMR_M: {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  AFGSTANGOVGDP: {
    family: "numeric-measurement",
    indicator_type: "ratio",
    temporal_aggregation: "not-applicable",
    heat_map_orientation: "neutral",
  },
  IRFCLDT1_IRFCL65_USD_IRFCL13: {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  ESPELEPRI: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  AFGHANISTAMINPRO: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  SINGAPORESERSEN: {
    family: "qualitative",
    indicator_type: "sentiment",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  NEWZEALANGDTPI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
  },
  AUSTRALIAJOBADV: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  ALBANIAPROPRICHA: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "lower-is-positive",
  },
  BRAMMIRM: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "lower-is-positive",
  },
  ALBANIAINDCTION: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  JPNTNMO: {
    family: "qualitative",
    indicator_type: "sentiment",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  PFX_LS_PAK_PKR: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  UFX_WB_CAF_XAF: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  AFGSTANEXPXPORTS: {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  MEXMMCIRM: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "lower-is-positive",
  },
  NGDPPC: {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  NGDP: {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  DNKMPMOM: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  SPEXPNOOA: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  USACPI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  AGOFYGG: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  AUSIIC: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  CANADAOILEXP: {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  CHNBCONDI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  UNITEDSTALIC: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  UNITEDSTANAHHOUMARIN: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  TMG_RPCH: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "neutral",
  },
  TD_RESERVES_GFR_LS_AGO_M: {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  "NE.IMP.GNFS.KD.ZG": {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "neutral",
  },
  AFGHANISTAGSTG: {
    family: "numeric-measurement",
    indicator_type: "ratio",
    temporal_aggregation: "period-average",
    heat_map_orientation: "neutral",
  },
  AFGHANISTAGDPFROMAN: {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  USAKFEI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  AUSIIM: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  JAPANTERINDIND: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  USAKFPPI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "period-average",
    heat_map_orientation: "lower-is-positive",
  },
  NGDPRPC: {
    family: "numeric-measurement",
    indicator_type: "ratio",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
    is_monetary: true,
  },
  AUSTRALIASERPMI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "period-average",
    heat_map_orientation: "higher-is-positive",
  },
  DEUIFOEXP: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "period-average",
    heat_map_orientation: "higher-is-positive",
  },
  CANADABUSCLIIND: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "period-average",
    heat_map_orientation: "higher-is-positive",
  },
  AUSIIBS: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "period-average",
    heat_map_orientation: "higher-is-positive",
  },
  AURPP: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "neutral",
  },
  USAPFPP: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "period-average",
    heat_map_orientation: "lower-is-positive",
  },
  "DT.DOD.DLXF.CD": {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
    is_monetary: true,
  },
  ARGENTINAEXPPRI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  USAIMP: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  UNITEDKINNATHOUPRI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
  },
  ALBWAGEGROWTH: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  UNITEDKINCLACOUCHA: {
    family: "numeric-measurement",
    indicator_type: "count",
    temporal_aggregation: "period-cumulative",
    heat_map_orientation: "lower-is-positive",
  },
  UNITEDSTAPCEPRIIND: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  ARGENTINACORCONPRI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  USAINMP: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  AFGHANISTACONPRIINDC: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  USADFMPPI: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
  },
  "DT.DOD.DIMF.CD": {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  CHNFDIY: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  CHNNHSY: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  "DT.DOD.DSTC.CD": {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
    is_monetary: true,
  },
  POLECY: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  AUSTRALIAEMPCHA: {
    family: "numeric-measurement",
    indicator_type: "count",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
  },
  ALGERIACHAININV: {
    family: "physical-fundamental",
    indicator_type: "balance",
    temporal_aggregation: "period-total",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  JPNHSY: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "higher-is-positive",
  },
  JPNEWSO: {
    family: "qualitative",
    indicator_type: "sentiment",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  JPNTLMO: {
    family: "qualitative",
    indicator_type: "sentiment",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  ARGENTINATEROFTRA: {
    family: "composite-derived",
    indicator_type: "index",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  "DT.AMT.DLXF.CD": {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "lower-is-positive",
    is_monetary: true,
  },
  UNITEDSTANETLONTICFL: {
    family: "physical-fundamental",
    indicator_type: "flow",
    temporal_aggregation: "period-total",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  ALBANIAGOVDEB: {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "lower-is-positive",
    is_monetary: true,
  },
  CHNDIL: {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  UNITEDSTAJC4A: {
    family: "numeric-measurement",
    indicator_type: "count",
    temporal_aggregation: "period-average",
    heat_map_orientation: "lower-is-positive",
  },
  AUNURS: {
    family: "numeric-measurement",
    indicator_type: "ratio",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  AUPHYS: {
    family: "numeric-measurement",
    indicator_type: "ratio",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "higher-is-positive",
  },
  IDNMOTSAL: {
    family: "physical-fundamental",
    indicator_type: "volume",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
  },
  AUSTRALIATOTVEHSAL: {
    family: "physical-fundamental",
    indicator_type: "volume",
    temporal_aggregation: "period-total",
    heat_map_orientation: "higher-is-positive",
  },
  AFGHANISTACORINFRAT: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "lower-is-positive",
  },
  UFX_WB_LKA_LKR: {
    family: "price-value",
    indicator_type: "price",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
    is_monetary: true,
  },
  UNITEDSTAAPICUSNUM: {
    family: "physical-fundamental",
    indicator_type: "stock",
    temporal_aggregation: "point-in-time",
    heat_map_orientation: "neutral",
  },
  AUSIPM: {
    family: "change-movement",
    indicator_type: "rate",
    temporal_aggregation: "period-rate",
    heat_map_orientation: "lower-is-positive",
  },
};

console.log(
  `Found ${
    Object.keys(agentClassifications).length
  } classifications from agents`,
);
console.log("✅ Classification data loaded successfully");
